
import asyncio
import random
import sys
from datetime import date, timedelta
from typing import List

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

# Add project root to path
import os
sys.path.append(os.getcwd())

from app.database import engine, init_db, async_session_maker
from app.models import Machine, Event, CharacteristicValue, PatrolResult
from app.services import dummy_data

# Constants from dummy_data (reusing for consistency)
MODEL_SERIES = ["A", "B", "C"]
MODEL_NUMBERS = {
    "A": ["A100", "A200", "A300"],
    "B": ["B100", "B200"],
    "C": ["C100", "C200", "C300", "C400"],
}
EVENT_TYPES = ["FW更新", "部品交換", "メンテナンス", "不具合発生"]
EVENT_CATEGORIES = ["動作不良", "センサー異常", "通信エラー", "部品劣化"]
DEFECT_CODES = [f"E{i}" for i in range(101, 120)]
PATROL_LOGICS = ["温度異常検知", "振動異常検知", "通信切断検知", "モーター過負荷検知", "電圧低下検知"]
FW_VERSIONS = ["1.0.0", "1.1.0", "1.2.0", "2.0.0", "2.1.0", "2.2.0"]

async def seed_machines(session: AsyncSession, count: int = 50) -> List[Machine]:
    """Seed machines"""
    print(f"Seeding {count} machines...")
    machines = []
    
    # Generate some consistent machines for demo
    # We want some machines from each series
    
    existing_machine_numbers = set()
    
    for i in range(count):
        series = random.choice(MODEL_SERIES)
        model = random.choice(MODEL_NUMBERS[series])
        
        # Ensure unique machine number
        while True:
            machine_number = f"{series}-{model}-{random.randint(1000, 9999)}"
            if machine_number not in existing_machine_numbers:
                existing_machine_numbers.add(machine_number)
                break
        
        # Manufacture date: 2020-2024
        manufacture_start = date(2020, 1, 1)
        manufacture_days = random.randint(0, 365 * 5)
        manufacture_month = manufacture_start + timedelta(days=manufacture_days)
        manufacture_month = manufacture_month.replace(day=1)
        
        # Operation start
        operation_offset = random.randint(30, 180)
        operation_start_month = manufacture_month + timedelta(days=operation_offset)
        operation_start_month = operation_start_month.replace(day=1)
        
        machine = Machine(
            machine_number=machine_number,
            model_series=series,
            model_number=model,
            manufacture_month=manufacture_month,
            operation_start_month=operation_start_month,
            option_config='{"option1": true, "option2": false}',
            current_fw_version=random.choice(FW_VERSIONS),
            total_usage_count=random.randint(1000, 1000000),
        )
        session.add(machine)
        machines.append(machine)
        
    await session.commit()
    print("Machines seeded.")
    return machines

async def seed_events(session: AsyncSession, machines: List[Machine]):
    """Seed events for each machine"""
    print("Seeding events...")
    
    for machine in machines:
        # Generate random events
        event_count = random.randint(5, 20)
        base_date = machine.operation_start_month or date(2021, 1, 1)
        current_fw = "1.0.0"
        usage = 0
        
        for i in range(event_count):
             # Spread events over time
            day_offset = random.randint(1, 1000)
            event_date = base_date + timedelta(days=day_offset)
            if event_date > date.today():
                continue
                
            event_type = random.choice(EVENT_TYPES)
            event_code = None
            event_category = None
            
            if event_type == "FW更新":
                current_fw = random.choice(FW_VERSIONS)
            elif event_type == "不具合発生":
                event_code = random.choice(DEFECT_CODES)
                event_category = random.choice(EVENT_CATEGORIES)
                
            usage += random.randint(500, 5000)
            
            event = Event(
                machine_id=machine.id,
                event_date=event_date,
                event_type=event_type,
                # event_code, event_category
                event_code=event_code,
                event_category=event_category,
                description=f"{event_type} generated by seed.",
                fw_version=current_fw,
                usage_count=usage
            )
            session.add(event)
            
    await session.commit()
    print("Events seeded.")

async def seed_characteristics(session: AsyncSession, machines: List[Machine]):
    """Seed characteristic values"""
    print("Seeding characteristics (this may take a while)...")
    
    # Only seed for a few machines to save time, or seed sparse data
    target_machines = machines[:20] # Seed first 20 full data
    
    categories = dummy_data.CHARACTERISTIC_CATEGORIES
    
    for machine in target_machines:
        # Generate monthly data from operation start to today
        start_date = machine.operation_start_month or date(2021, 1, 1)
        end_date = date.today()
        
        current = start_date.replace(day=1)
        usage = 0
        
        while current <= end_date:
            usage += random.randint(2000, 5000)
            
            for cat in categories:
                # Generate values for IDs in this category
                ids = dummy_data.CHARACTERISTIC_IDS.get(cat, [])
                for cid in ids:
                    # Simple random generation
                    val = random.gauss(50, 10)
                    
                    cv = CharacteristicValue(
                        machine_id=machine.id,
                        record_date=current,
                        category=cat,
                        characteristic_id=cid,
                        value_numeric=val,
                        value_text=None,
                        usage_count=usage
                    )
                    session.add(cv)
            
            # Next month
            if current.month == 12:
                current = current.replace(year=current.year + 1, month=1)
            else:
                current = current.replace(month=current.month + 1)
                
    await session.commit()
    print("Characteristics seeded.")

async def seed_patrol_results(session: AsyncSession, machines: List[Machine]):
    """Seed patrol results"""
    print("Seeding patrol results...")
    
    # Generate random patrol results linked to existing machines (or not)
    # The spec allows patrol results for machines that might not be in our DB? 
    # Usually they should exist. We will link them by string machine_id.
    
    count = 100
    
    for i in range(count):
        machine = random.choice(machines)
        patrol_date = date.today() - timedelta(days=random.randint(0, 60))
        
        rank = random.choice(["A", "B", "C"])
        alert = False
        if rank == "A": alert = random.random() > 0.5
        
        pr = PatrolResult(
            patrol_date=patrol_date,
            rank=rank,
            series=machine.model_series,
            model=machine.model_number,
            machine_id=machine.machine_number,
            defect_category=random.choice(EVENT_CATEGORIES),
            defect_code=random.choice(DEFECT_CODES),
            defect_count=random.randint(1, 5),
            logic_content=random.choice(PATROL_LOGICS),
            alert_flag=alert,
            description="Detected by patrol logic."
        )
        session.add(pr)
        
    await session.commit()
    print("Patrol results seeded.")

async def main():
    print("Initializing Database...")
    await init_db()
    
    async with async_session_maker() as session:
        # Clear existing data?
        # For now, just add.
        
        machines = await seed_machines(session, count=50)
        await seed_events(session, machines)
        await seed_characteristics(session, machines)
        await seed_patrol_results(session, machines)
        
    print("Seeding complete!")

if __name__ == "__main__":
    asyncio.run(main())
